# Generated by Django 2.0.1 on 2018-02-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0013_auto_20180202_1522'),
        ('customer', '0003_auto_20180201_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='retaildeal',
            name='dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.Dealership'),
        ),
        migrations.AddField(
            model_name='retaildeal',
            name='status',
            field=models.CharField(choices=[('Y', 'Accept'), ('N', 'Reject'), ('W', 'Waiting')], default='W', max_length=2),
        ),
    ]
