# Generated by Django 2.0.1 on 2018-01-25 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalecar',
            name='in_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wholesalecar',
            name='manufacturer_inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.ManufacturerInventory'),
        ),
    ]
