# Generated by Django 2.0.1 on 2018-01-25 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_auto_20180125_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufactureradmin',
            name='manufacturer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.Manufacturer'),
        ),
    ]
