# Generated by Django 2.0.1 on 2018-01-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0007_auto_20180126_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesalecar',
            name='in_inventory',
        ),
    ]
