# Generated by Django 2.0.1 on 2018-01-28 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0008_remove_wholesalecar_in_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufactureradmin',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing.Manufacturer'),
        ),
    ]
