# Generated by Django 2.0.1 on 2018-01-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0009_auto_20180128_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufactureradmin',
            options={'permissions': (('manufacturer_admin', 'Manufacturer Admin Rights'),)},
        ),
    ]
