# Generated by Django 2.0.1 on 2018-02-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0010_auto_20180131_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturerinventory',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='wholesalecar',
            name='manufacturer_inventory',
        ),
        migrations.AddField(
            model_name='wholesalecar',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.Manufacturer'),
        ),
        migrations.DeleteModel(
            name='ManufacturerInventory',
        ),
    ]
