# Generated by Django 2.0.1 on 2018-01-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_auto_20180129_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaledeal',
            name='status',
            field=models.CharField(choices=[('Y', 'Accept'), ('N', 'Reject'), ('W', 'Waiting')], default='W', max_length=2),
        ),
    ]
