# Generated by Django 2.0.1 on 2018-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0003_wholesaledeal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailcar',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
