# Generated by Django 2.0.1 on 2018-01-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0004_auto_20180129_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailcar',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
