# Generated by Django 2.0.1 on 2018-01-30 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0006_wholesaledeal_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaledeal',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dealership.DealershipAdmin'),
        ),
    ]
