# Generated by Django 2.0.1 on 2018-01-30 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0008_auto_20180130_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaledeal',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
