# Generated by Django 2.0.1 on 2018-01-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0009_auto_20180130_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealershipadmin',
            options={'permissions': (('dealership_admin', 'Dealership Admin Rights'),)},
        ),
    ]
