# Generated by Django 2.0.1 on 2018-02-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0010_auto_20180131_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailcar',
            name='quantity',
        ),
    ]
