# Generated by Django 2.0.1 on 2018-02-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0012_auto_20180202_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaledeal',
            name='car_amount',
            field=models.IntegerField(default=1),
        ),
    ]
