# Generated by Django 2.0.1 on 2018-02-06 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0013_auto_20180202_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaledeal',
            name='car_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturing.WholesaleCar'),
        ),
    ]
