# Generated by Django 2.0.1 on 2018-02-06 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0014_auto_20180206_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholesaledeal',
            name='car_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.WholesaleCar'),
        ),
    ]
